name: Koni Dev
on:
  pull_request: { }
  push:
    branches:
      - koni-dev
      - upgrade-ui
      - test-ci

jobs:
  master:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-22.04
    name: Build Development Preview
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    - name: Build Dev
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        GH_PAT: ${{ secrets.GH_PAT }}
        GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        NEXTCLOUD_CONFIG: ${{ secrets.NEXTCLOUD_CONFIG }}
        TRANSAK_API_KEY: ${{ secrets.TRANSAK_API_KEY }}
        COINBASE_PAY_ID: ${{ secrets.COINBASE_PAY_ID }}
        GH_RELEASE_FILES: master-build.zip,master-src.zip
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        REF_NAME: ${{ github.ref_name }}
        PR_NUMBER: ${{ github.event.number }}
        TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
        CURRENT_BRANCH: ${{ github.event.pull_request.head.ref || github.ref }}
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn build:koni-dev
    - name: Deploy Webrunner to Netlify
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: './packages/web-runner/build'
        alias: ${{ github.head_ref }}
        github-token: ${{ secrets.GH_PAT }}
        deploy-message: ${{ github.event.head_commit.message }}
        enable-pull-request-comment: true
        enable-commit-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WEB_RUNNER_SITE_ID }}
      timeout-minutes: 1

